# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

variables:
  
  - group: frontend-variables # Variable Group containing dockerhub userid and password

  - name: dockerRegistryServiceConnection
    value: 'containerRegistryConnection' # make sure it matches the name you used in the service connection
  
  - name: acrEndpoint
    value: 'akstest2020.azurecr.io' # replace with container registry endpoint

  - name: tag
    value: '$(Build.BuildId)'

name: $(build.sourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: '$(dockerId)/frontend'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
  
- script: docker login -u $(dockerId) -p $(dockerPassword)
  displayName: 'docker login'

- script: docker push $(imageName)
  displayName: 'docker push latest if this is the master branch'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: |
        docker tag $(imageName) $(imageName):$(build.buildNumber)
        docker push $(imageName):$(build.buildNumber)
  displayName: 'docker push with build number'